const initialState = {
  menuCategories: {
    MOMOS: [
      { name: "Veg Steamed Momos", price: 99 },
      { name: "Veg Fried Momos", price: 109 },
      { name: "Veg Crispy Momos", price: 129 },
      { name: "Veg Chili Momos", price: 139 },
      { name: "Veg Afghani Momos", price: 139 },
      { name: "Veg Kadai Momos", price: 139 },
      { name: "Veg Cocktail Momos", price: 149 },
      { name: "Veg Tandoori Momos", price: 139 },
      { name: "Paneer Steamed Momos", price: 119 },
      { name: "Paneer Fried Momos", price: 129 },
      { name: "Paneer Crispy Momos", price: 159 },
      { name: "Paneer Tandoori Momos", price: 159 },
      { name: "Paneer Chili Momos", price: 159 },
      { name: "Paneer Kadai Momos", price: 159 },
      { name: "Paneer Afghani Momos", price: 159 },
      { name: "Paneer Cocktail Momos", price: 189 },
      { name: "Chicken Steamed Momos", price: 129 },
      { name: "Chicken Crispy Momos", price: 169 },
      { name: "Chicken Chili Momos", price: 169 },
      { name: "Chicken Fried Momos", price: 149 },
      { name: "Chicken Afghani Momos", price: 169 },
      { name: "Chicken Cocktail Momos", price: 199 },
      { name: "Chicken Tandoori Momos", price: 169 },
    ],
    "SANDWICH & BURGERS": [
      { name: "Classic Veg Burger", price: 149 },
      { name: "Aloo Tikki Burger", price: 129 },
      { name: "Classic Veg Cheese Burger", price: 169 },
      { name: "Paneer Cheese Burger", price: 189 },
      { name: "Classic Chicken Burger", price: 169 },
      { name: "Chicken Cheese Burger", price: 189 },
      { name: "Sidewalk Special", price: 199 },
      { name: "Veg Classic Sandwich", price: 109 },
      { name: "Veg Classic Cheese Sandwich", price: 129 },
      { name: "Veg Coleslaw Sandwich", price: 149 },
      { name: "Cheese Sandwich", price: 149 },
      { name: "Paneer Tikka Sandwich", price: 229 },
      { name: "Classic Chicken  sandwich", price: 149 },
      { name: "Chicken Cheese Sandwich", price: 169 },
      { name: "Chicken Tikka Sandwich", price: 239 },
      { name: "Vegetable Cheese Toast", price: 149 },
      { name: "Vegetable Chili Cheese Toast", price: 169 },
      { name: "Chicken Cheese Toast", price: 189 },
    ],
    MUNCHIES: [
      { name: "Classic French Fries", price: 109 },
      { name: "Peri Peri French Fries", price: 129 },
      { name: "Cheesy French Fries", price: 139 },
      { name: "Peri Peri Cheesy Dipped French Fries", price: 149 },
      { name: "Masala Corn", price: 109 },
      { name: "Crispy Corn", price: 129 },
      { name: "Chicken Nuggets", price: 169 },
      { name: "Chicken Popcorn", price: 169 },
      { name: "Crispy Chicken Cheese Balls", price: 189 },
      { name: "Peri Peri Fried Chicken Wings ", price: 199 },
      { name: "Devil Chicken", price: 199 },
      { name: "Spicy BBQ Crispy Chicken Wings", price: 229 },
      { name: "Cheese Garlic Bread", price: 149 },
      { name: "Chili Cheese Garlic Bread", price: 169 },
      { name: "Corn Cheese Balls", price: 179 },
    ],
    MAGGIE: [
      { name: "Masala Maggi", price: 79 },
      { name: "Vegetable Maggi", price: 99 },
      { name: "Vegetable Cheese Maggi", price: 119 },
      { name: "Peri Peri Veg Cheese Maggi", price: 129 },
      { name: "Egg Maggi", price: 129 },
      { name: "Cheese Egg Maggi", price: 149 },
      { name: "Chicken Maggi", price: 149 },
      { name: "Chicken Cheese Maggi", price: 169 },
      { name: "Peri Peri Chicken Cheese Maggi", price: 179 },
    ],
    SOUP: [
      { name: "Veg Manchow Soup", price: 129 },
      { name: "Sweet Corn Soup", price: 129 },
      { name: "Lemon Coriander Soup", price: 129 },
      { name: "Tomato Soup", price: 129 },
      { name: "Veg Hot N Sour Soup", price: 129 },
      { name: "Veg Clear Soup", price: 99 },
      { name: "Chicken Sweet Corn Soup", price: 149 },
      { name: "Chicken Manchow Soup", price: 149 },
      { name: "Chicken Hot N Sour Soup", price: 149 },
      { name: "Chicken Clear Soup", price: 119 },
    ],
    "CHINESE-STARTERS": [
      { name: "Veg Kot", price: 169 },
      { name: "Sesame Roll", price: 169 },
      { name: "Spider Roll", price: 169 },
      { name: "Honey Chili Potato", price: 169 },
      { name: "Baby Corn Chili", price: 199 },
      { name: "Mushroom Chili", price: 199 },
      { name: "Veg Manchurian", price: 199 },
      { name: "Veg Spring Roll", price: 199 },
      { name: "Veg Saute", price: 199 },
      { name: "Paneer Chili", price: 229 },
      { name: "Paneer Satay", price: 229 },
      { name: "Paneer 65", price: 249 },
    ],
    "NOODLES & RICE": [
      { name: "Veg Hakka Noodles", price: 179 },
      { name: "Veg Schezwan Noodles", price: 189 },
      { name: "Veg. Chili Garlic Noodles", price: 189 },
      { name: "Veg Burnt Garlic Noodles", price: 189 },
      { name: "Veg American Choupsey", price: 209 },
      { name: "Egg Hakka Noodles", price: 199 },
      { name: "Egg Schezwan Noodles", price: 209 },
      { name: "Chicken Hakka Noodles", price: 219 },
      { name: "Chicken Schezwan Noodles", price: 229 },
      { name: "Chicken Chili Garlic Noodles", price: 229 },
      { name: "Chicken Burnt Garlic Noodles", price: 229 },
      { name: "Chicken American Choupsey", price: 239 },
      { name: "Veg Fried Rice", price: 179 },
      { name: "Veg Schezwan Fried Rice", price: 189 },
      { name: "Veg Burnt Garlic Fried Rice", price: 189 },
      { name: "Veg Triple Schezwan Fried Rice", price: 229 },
      { name: "Egg Fried Rice", price: 199 },
      { name: "Chicken Fried Rice", price: 229 },
      { name: "Chicken Schezwan Fried Rice", price: 239 },
      { name: "Chicken Burnt Garlic Fried Rice", price: 239 },
      { name: "Chicken Triple Schezwan Fried Rice", price: 279 },
    ],
    PASTA: [
      {
        name: "Alfredo Pasta (Penne / Spaghetti) (Veg / Chicken)",
        price: "229 / 269",
      },
      {
        name: "Arabiata Pasta (Penne / Spaghetti) (Veg / Chicken)",
        price: "229 / 269",
      },
      {
        name: "Pink Sauce Pata (Penne / Spaghetti) (Veg / Chicken)",
        price: "229 / 269",
      },
    ],
    TANDOOR: [
      { name: "Veg Seekh Kebab", price: 169 },
      { name: "Veg Hara Bhara Kebab", price: 169 },
      { name: "Dahi Kebab", price: 169 },
      { name: "Mushroom Tikka", price: 199 },
      { name: "Paneer Tikka", price: 229 },
      { name: "Flavour Paneer Tikka ", price: 249 },
      { name: "Paneer Malai Tikka", price: 269 },
      { name: "Paneer Stuffed Tikka", price: 299 },
      { name: "Chicken Seekh Kebab", price: 219 },
      { name: "Chicken Tikka", price: 229 },
      { name: "Chicken Flavoured Tikka", price: 249 },
      { name: "Chicken Malai Tikka", price: 269 },
      { name: "Chicken Reshami Tikka", price: 269 },
      { name: "Afghani Chicken", price: "259 / 399" },
      { name: "Lazeez Tangdi", price: 259 },
      { name: "Punjabi Tangdi", price: 249 },
      { name: "Tandoori Chicken", price: "249 / 399" },
      { name: "Fish Tikka", price: 269 },
      { name: "Flavour Fish Tikka", price: 289 },
      { name: "Mutton Seekh Kebab", price: 279 },
    ],
    "MAINCOURSE INDIAN": [
      { name: "Dal Fry / Dal Tadka", price: 149 },
      { name: "Dal Makhani", price: 199 },
      { name: "Aaloo Jeera", price: 149 },
      { name: "Kashmiri Aaloo", price: 149 },
      { name: "Aaloo Dum Punjabi", price: 149 },
      { name: "Mix Veg", price: 199 },
      { name: "Veg Kolhapuri", price: 199 },
      { name: "Veg Jalfraji", price: 219 },
      { name: "Veg Hyderabadi", price: 219 },
      { name: "Bhindi Masala", price: 199 },
      { name: "Mushroom Kadai", price: 229 },
      { name: "Mushroom Masala", price: 229 },
      { name: "Seasonal Veg", price: 199 },
      { name: "Paneer Do Pyaza", price: 229 },
      { name: "Kadai Paneer", price: 229 },
      { name: "Malai Kofta", price: 239 },
      { name: "Paneer Kolhapuri", price: 239 },
      { name: "Butter Paneer Masala", price: 249 },
      { name: "Paneer Tikka Masala", price: 269 },
      { name: "Paneer Tikka Lababdar", price: 279 },
      { name: "Sahi Paneer", price: 279 },
      { name: "Paneer Sahi Korma", price: 289 },
      { name: "Egg Curry", price: 199 },
      { name: "Egg Masala", price: 199 },
      { name: "Chicken Curry", price: 269 },
      { name: "Chicken Masala", price: 279 },
      { name: "Butter Chicken", price: 299 },
      { name: "Kadai Chicken", price: 289 },
      { name: "Chicken Saagwala", price: 289 },
      { name: "Chicken Tikka Lababdar", price: 319 },
      { name: "Chicken Tikka Masala ", price: 299 },
      { name: "Chicken Butter Masala", price: 319 },
      { name: "Chicken Afghani Gravy", price: 319 },
      { name: "Peshawari Chicken", price: 349 },
      { name: "Chicken Dehati", price: 349 },
      { name: "Chicken Punjabi Tangdi Masala", price: 319 },
      { name: "Murg Musallam", price: 499 },
      { name: "Mutton Curry", price: 399 },
      { name: "Mutton Rogan Josh", price: 399 },
      { name: "Muttan Bhuna", price: 399 },
      { name: "Mutton Rara Ghost", price: 429 },
    ],
    "RICE & BIRYANI": [
      { name: "Steamed Rice", price: 99 },
      { name: "Jeera Rice", price: 149 },
      { name: "Veg Pulao", price: 179 },
      { name: "Masala Rice", price: 179 },
      { name: "Vegetable Dum Biryani", price: 199 },
      { name: "Egg Dum Biryani", price: 209 },
      { name: "Chicken Dum Biryani", price: 299 },
      { name: "Hyderabadi Biryani", price: 279 },
      { name: "Chicken Tikka Biryani", price: 289 },
      { name: "Mutton Biryani", price: 399 },
    ],
    BREAD: [
      { name: "Butter Tandoori Roti", price: 25 },
      { name: "Plain Naan", price: 35 },
      { name: "Butter Naan", price: 45 },
      { name: "Butter Garlic Naan", price: 50 },
      { name: "Cheese Naan", price: 60 },
      { name: "Chili Cheese Naan", price: 65 },
      { name: "Stffed Naan (Paneer / Chicken )", price: "89 / 109" },
      { name: "Lachha Paratha", price: 40 },
      { name: "Paratha ( Aaloo / Paneer / Chicken )", price: "69 / 99 / 109" },
      { name: "Pudina Paratha", price: 60 },
      { name: "Butter Kulcha", price: 40 },
      { name: "Missi Roti", price: 40 },
      { name: "Roti Basket", price: 199 },
    ],
    COMBOS: [
      {
        name: "Veg Hakka Noodles / Veg Fried Rice + Veg Manchurian +Veg Spring Roll",
        price: 299,
      },
      {
        name: "Chicken Hakka Noodles/Chicken Momos+ Chicken Chili + Chicken Spring Roll",
        price: 349,
      },
    ],
    SHAKES: [
      { name: "Vanilla Shake", price: 129 },
      { name: "Banana Shake", price: 149 },
      { name: "Nutella Shake", price: 249 },
      { name: "Oreo Shake", price: 159 },
      { name: "KitKat Shake", price: 159 },
      { name: "Brownie Shake", price: 229 },
      { name: "KitKat Oreo Shake", price: 249 },
      { name: "Dark Chocolate Shake", price: 159 },
      { name: "Strawberry Shake", price: 149 },
      { name: "Bubblegum Shake", price: 159 },
      { name: "Mango Shake", price: 149 },
      { name: "Butterscotch Shake", price: 159 },
      { name: "Tutti Futti Shake", price: 169 },
      { name: "Bluberry Shake", price: 159 },
      { name: "KitKat Oreo Freak Shake", price: 329 },
      { name: "Red Velvet Freak Shake", price: 329 },
      { name: "Nutella Oreo Shake", price: 329 },
      { name: "Caramel Popcorn Shake", price: 329 },
    ],
    MOCKTAILS: [
      { name: "Virgin Mojito", price: 149 },
      { name: "Flavoured Mojito (Apple / Peach)", price: 159 },
      { name: "Mango Mint Cooler", price: 169 },
      { name: "Strawberry Margarita", price: 169 },
      { name: "Hawaiian Sunrise", price: 169 },
      { name: "Strawberry Fizz", price: 169 },
      { name: "Electrical Blue", price: 169 },
      { name: "Sex On The Beach", price: 169 },
      { name: "Black Beauty", price: 169 },
      { name: "Kiwi Spicy", price: 169 },
      { name: "Blue Lagoon", price: 129 },
      { name: "Pina Colada", price: 129 },
      { name: "Bloody Mary", price: 169 },
      { name: "Coke", price: 59 },
      { name: "Sprite", price: 59 },
      { name: "Masala Coke", price: 79 },
      { name: "Fresh Lime Water", price: 129 },
      { name: "Fresh Lime Soda ", price: 149 },
      { name: "Masala Lemonade", price: 149 },
      { name: "Lemon Iced Tea", price: 149 },
      { name: "Peach Iced Tea", price: 149 },
      { name: "Red Bull", price: 145 },
      { name: "Heineken", price: 149 },
    ],
    DESERT: [
      { name: "Caramel Custard", price: 149 },
      { name: "Brownie", price: 99 },
      { name: "Hot Brownie With Ice Cream", price: 169 },
      { name: "Sizzling Brownie With Ice Cream", price: 219 },
      { name: "Fried Ice Cream", price: 149 },
    ],
  },
  isMenuLayout: false,
};

export default function (state = initialState, action) {
  switch (action.type) {
    case "SET_MENU_CATEGORIES":
      return {
        ...state,
        menuCategories: action.payload,
      };

    case "IS_MENU_POPUP":
      return {
        ...state,
        isMenuLayout: action.payload,
      };

    default:
      return {
        ...state,
      };
  }
}
